# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VehicleConnect' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VehicleConnect
    pod 'AppAuth', '1.7.6'
    pod 'SwiftLint'
    pod 'VehicleConnectSDK'
  
  target 'VehicleConnectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VehicleConnectUITests' do
    # Pods for testing
  end

end

