# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VehicleConnect' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VehicleConnect
    pod 'AppAuth', '1.7.5'
    pod 'SwiftLint', '0.55.1'
  
  target 'VehicleConnectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VehicleConnectUITests' do
    # Pods for testing
  end


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
