name: iOS starter workflow
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    steps:
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.4.app
      - name: Build Cleanup
        run: |
         rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependencies install
        run: |
         cd VehicleConnect
         pod deintegrate
         pod install --repo-update --clean-install
      - name: Set Default Scheme
        run: |
          cd VehicleConnect
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          cd VehicleConnect
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"

      # Step 3: Upload the ipa file to an artifact
      - name: Upload build file
        uses: actions/upload-artifact@v4
        with:
          name: app_release
          path: artifacts/app_release.ipa
